version: "3.9"

services:
  #database
  mysql_db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  # backend
  backend:
    build: .
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql_db
    links:
      - minio
    restart: unless-stopped

  #minio
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-09-22T18-57-27Z
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - miniodata:/data
    hostname: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: http://localhost:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

volumes:
  mysql:
  miniodata: