version: "3.9"

services:
  #database
  mysql_db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  # backend
  backend:
    build: .
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql_db
    restart: unless-stopped

volumes:
  mysql: